(define (problem Planificaio)
   (:domain Planificacio)
   (:objects rover1 - rover
        p1 p2 p3 p4 p5 - personal
        s1 s2 s3 s4 s5 - subministrament
        a1 a2 a3 a4 a5 - assentament
        m1 m2 m3 m4 m5 - magatzem
    )

   (:init
     (estacionat rover1 a1)
     (cami a1 m1)
     (cami m1 a2)
     (cami a2 m2)
     (cami m2 a3)
     (cami a3 m3)
     (cami m3 a4)
     (cami a4 m4)
     (cami m4 a5)
     (cami a5 m5)
     (cami m5 a1)
     (disponible p1 a1)
     (disponible p2 a1)
     (disponible p3 a1)
     (disponible p4 a1)
     (disponible p5 a1)
     (disponible s1 m5)
     (disponible s2 m5)
     (disponible s3 m5)
     (disponible s4 m5)
     (disponible s5 m5)
     (peticio p1 a5)
     (peticio p2 a5)
     (peticio p3 a5)
     (peticio p4 a5)
     (peticio p5 a5)
     (peticio s1 a5)
     (peticio s2 a5)
     (peticio s3 a5)
     (peticio s4 a5)
     (peticio s5 a5)
   )
   (:goal (and (forall (?o - personal) (servit ?o)) (forall (?o - subministrament) (servit ?o)))
   )
)